### ISSUE TITLE
Error: A newer Command Line Tools release is available.

### ISSUE THREAD

**Issue by Mitsuhamizu** [nervosnetwork/homebrew-tap#4]
I just want to use the ckb-sdk-ruby. And I just followed the README.md.

After I running the command "brew install libsecp256k1"

It report an error saying 

```
>Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

==> Cloning https://github.com/bitcoin/secp256k1.git
Updating /Users/ZhiChunLu/Library/Caches/Homebrew/libsecp256k1--git
==> Checking out revision fa3301713549d118e57ebe6551d062903ddd6b63
HEAD is now at fa33017 Merge #634: Add a descriptive comment for secp256k1_ecmult_const.
HEAD is now at fa33017 Merge #634: Add a descriptive comment for secp256k1_ecmult_const.
==> ./autogen.sh
==> ./configure prefix=/usr/local/Cellar/libsecp256k1/2019.06.12.fa3301 --disable-
==> make
==> ./tests
Last 15 lines from /Users/ZhiChunLu/Library/Logs/Homebrew/libsecp256k1/04.tests:
2020-05-19 19:43:07 +0800

./tests


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/nervosnetwork/homebrew-tap/issues


Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.
```

I have checked that my command line tools is the latest, and the error only happens after this command...

**Comment by doitian** [comment]
You can run `brew doctor` to see whether there are any errors.

Or try to remove command tool and reinstall

```
sudo rm -r -f /Library/Developer/CommandLineTools
xcode-select --install
```

A brew formula just automates the build. You can always build libsecp256k1 yourself.

**Comment by doitian** [comment]
Clone secp and build manually:

```
./autogen.sh
./configure --disable-silent-rules --enable-module-recovery
make
make install
```

**Comment by Mitsuhamizu** [comment]
> You can run `brew doctor` to see whether there are any errors.
> 
> Or try to remove command tool and reinstall
> 
> ```
> sudo rm -r -f /Library/Developer/CommandLineTools
> xcode-select --install
> ```
> 
> A brew formula just automates the build. You can always build libsecp256k1 yourself.

It works for me, thanks!
